packages:
  - 'apps/*'
  - 'packages/*'

storeDir: .cache/pnpm-store
strictPeerDependencies: true
packageManagerStrict: true
packageManagerStrictVersion: true
managePackageManagerVersions: false
onlyBuiltDependencies: []
